language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  - hhvm

install:
  composer install

script: phpunit --configuration tests/phpunit.xml

notifications:
  recipients:
    - david.gorges@leaphub.de
  on_success: change
  on_failure: always